spring.application.name=exam-portfolio-backend

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Security
security.admin.email=${ADMIN_EMAIL}
security.admin.username=${ADMIN_USERNAME}
security.admin.password=${ADMIN_PASSWORD}

# Server
# Uses PORT environment variable on Render, falls back to 8080 locally
server.port=${PORT:8080}

# Resend API
resend.api.key=${RESEND_API_KEY}
recipient=${RECIPIENT}

# Logging

logging.level.com.david.examportfolio.exam_portfolio_backend=DEBUG

