spring.application.name=exam-portfolio-backend

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Security
spring.security.user.name=${SPRING_SECURITY_USER}
spring.security.user.password=${SPRING_SECURITY_PASSWORD}

# Server
server.port=8080